name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    
    - name: Cleanup legacy root files
      run: sudo rm -rf ${{ github.workspace }}/.scannerwork
      
    - name: Checkout
      uses: actions/checkout@v4

    # SonarQube Scan
    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@v2
      with:
        args: >
          -Dsonar.projectKey=llama-gitops
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        
    - name: Inject Model File
      run: |
        mkdir -p llama.cpp/models/
        cp /home/ec2-user/llama.cpp/llama.cpp/models/ChatWithRavikant.gguf ./llama.cpp/models/ChatWithRavikant.gguf


    # Build Docker Image
    - name: Build Image
      run: docker build -t rkg1983/llama:${{ github.sha }} .

    # Trivy Scan
    - name: Trivy Scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: rkg1983/llama:${{ github.sha }}
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'HIGH'
        trivy-config: |
           skip-dirs:
            - node_modules
            - .git
           

    # Push Image
    - name: Push Image
      run: |
        echo ${{ secrets.DOCKER_PASS }} | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin
        docker push rkg1983/llama:${{ github.sha }}

    # Update GitOps Repo
    - name: Update GitOps
      run: |
        git clone https://x-access-token:${{ secrets.TOKEN_GITHUB }}@github.com/ravikant1983/llama-gitops.git
        cd llama-gitops
        sed -i "s|image:.*|image: rkg1983/llama:${{ github.sha }}|g" deployment.yaml
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        git commit -am "update image"
        git push

        
